### ISSUE TITLE
Error running against tutorial msfragger files: KeyError: 'spectrum_neutral_mass'

### ISSUE THREAD

**Issue by mriffle** [freejstone/CONGA#15]
I'm running using Python 3.9, here is the output I get when running against the MSFragger tutorial files:

```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ne0te482 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
CPU: Linux-5.4.0-126-generic-x86_64-with-glibc2.31
2023-01-13 22:39:48.770941
Command used: /usr/local/bin/CONGA.py --seed 1 --score hyperscore narrow.tsv open.tsv tide-index.peptides.txt
Successfully read in arguments.
Reading in search files.
Successfully read in search files.
hyperscore successfully found in search files.
MS-Fragger search files detected.
Concatenated search files detected.
Rewriting peptide sequence in tide-search format.
Filtering for neighbours.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31168/31168 [00:21<00:00, 1470.87it/s]
Reading peptide list.
Doing head to head competition.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'spectrum_neutral_mass'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/CONGA.py", line 2249, in <module>
    main()
  File "/usr/local/bin/CONGA.py", line 1964, in main
    df = create_groups(target_decoys_all, narrow_target_decoys, peptide_list, dcy_prefix, K, tops_gw, score, account_mods, any_mods, precursor_bin_width, group_thresh, adaptive, min_group_size, n_top_groups, tide_used, print_group_pi0)
  File "/usr/local/bin/CONGA.py", line 1048, in create_groups
    spectrum_neutral_mass = target_decoys_final['spectrum_neutral_mass']
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'spectrum_neutral_mass'
```

**Comment by freejstone** [comment]
Thanks for catching these Mike. Should be fixed now. It was a recent push again. I will set up the automatic testing soon so I can avoid these types of problems. Cheers, Jack.

```
CPU: macOS-10.16-x86_64-i386-64bit 
2023-01-14 11:53:21.867237 
Command used: CONGA.py --score hyperscore docs/pages/files/MS/narrow.tsv docs/pages/files/MS/narrow.tsv docs/pages/files/MS/tide-index.peptides.txt
Successfully read in arguments. 
Reading in search files. 
Successfully read in search files. 
hyperscore successfully found in search files. 
MS-Fragger search files detected. 
Concatenated search files detected. 
Rewriting peptide sequence in tide-search format. 
Filtering for neighbours.
100%|███████████████████████████████████| 21803/21803 [00:09<00:00, 2306.99it/s]
Reading peptide list. 
Doing head to head competition.
Constructing groups adaptively.
              decoys  targets     ratio
group names:                           
narrow          4801    10742  0.446937
Applying group walk.
Group walk complete.
5258 peptides discovered at the 1% FDR level. 
6134 peptides discovered at the 5% FDR level. 
Scan multiplicities among the discovered peptides at 1% FDR level: 
                    Count
Scan multiplicity:       
1                    5258
Scan multiplicities among the discovered peptides at 5% FDR level: 
                    Count
Scan multiplicity:       
1                    6134
Writing peptides at user-specified FDR level to directory. 
Elapsed time: 17.87 s 

```

**Comment by freejstone** [comment]
Sorry I still need to push the updates still, won't be a moment

**Comment by freejstone** [comment]
Apologies for the delay, fix has been pushed.

**Comment by mriffle** [comment]
Thanks, works on my end!
